events {
}

http {
    upstream app {
        #ip_hash; # Mantém a sessão amarrada pelo IP do cliente
        server app:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://app;
        }
    }
}
